# Generated by Django 4.1 on 2022-08-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precision_paint_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
