# Generated by Django 4.1 on 2022-08-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precision_paint_api', '0003_alter_estimate_approved_alter_estimate_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
