# Generated by Django 4.1 on 2022-08-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precision_paint_api', '0004_alter_invoice_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
